### PR TITLE
Added "Rule Break"

### PR DESCRIPTION
**Pull request by jasonlav**
Added ability to add custom options for line breaks after each rule. Some front end developers prefer an additional line break after reach rule for enhanced readability.

My experience in Python is very limited, so I apologize in advance.

### CODE REVIEW

**Comment by elliottregan** [comment]
I'd love to see this merged!

**Comment by jonathanappel** [comment]
+1 for this.

**Comment by CaitlinWeb** [comment]
+1 as this is the only thing I feel this plugin lacks. It's the best CSS formatter for Sublime Text I've found, but I'd like `expand-bs` not to force linebreaks between rules.

**Comment by mutian** [comment]
First of all, I am very sorry that I have been especially busy in the past two years to deal with this problem until now.
Thank you very much for your patience, and the code you submitted has been merged.

**Pull request merged**
